---
# Docker role handlers

- name: Inform user to logout
  ansible.builtin.debug:
    msg: |
      IMPORTANT: Log out and back in for Docker group membership to take effect.
      You can then run Docker commands without sudo.
