---
# Configure Docker service and user permissions

- name: Add users to docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ dfe_docker_users }}"
  notify: Inform user to logout
  when: ansible_distribution in ['Fedora', 'Ubuntu']

- name: Enable and start Docker service
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started
  when: ansible_distribution in ['Fedora', 'Ubuntu']

# macOS - Docker Desktop manages its own service
