---
# Python development tools installation
# UV package manager only - manages Python versions and packages (replaces pip, pyenv, pipx)

# Install UV package manager (standalone, no dependencies needed)
- name: Download UV installer
  ansible.builtin.get_url:
    url: https://astral.sh/uv/install.sh
    dest: /tmp/uv-install.sh
    mode: '0755'
  become: false

- name: Install UV package manager
  ansible.builtin.shell: /tmp/uv-install.sh
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/bin/uv"
  become: false
  environment:
    CARGO_HOME: "{{ ansible_env.HOME }}/.cargo"

- name: Remove UV installer script
  ansible.builtin.file:
    path: /tmp/uv-install.sh
    state: absent
  become: false

- name: Display UV installation info
  ansible.builtin.debug:
    msg: |
      UV installed successfully
      Usage:
        uv python install 3.11      # Install Python 3.11
        uv python list               # List available Python versions
        uv venv                      # Create virtual environment
        uv pip install <package>     # Install packages
      UV replaces: pip, pyenv, pipx, virtualenv
