---
# Configure TLS certificates for GNOME Remote Desktop system service

- name: Create gnome-remote-desktop certificates directory
  ansible.builtin.file:
    path: /var/lib/gnome-remote-desktop/.local/share/gnome-remote-desktop/certificates
    state: directory
    mode: '0700'
    owner: gnome-remote-desktop
    group: gnome-remote-desktop
  when:
    - ansible_distribution in ['Fedora', 'Ubuntu']
    - dfe_has_gnome

- name: Generate self-signed certificate for RDP
  ansible.builtin.command:
    cmd: openssl req -new -newkey rsa:4096 -days 730 -nodes -x509 -subj "/C=AU/ST=NSW/L=Sydney/O=HyperSec/CN={{ ansible_hostname }}" -keyout /var/lib/gnome-remote-desktop/.local/share/gnome-remote-desktop/certificates/rdp-tls.key -out /var/lib/gnome-remote-desktop/.local/share/gnome-remote-desktop/certificates/rdp-tls.crt
  args:
    creates: /var/lib/gnome-remote-desktop/.local/share/gnome-remote-desktop/certificates/rdp-tls.crt
  when:
    - ansible_distribution in ['Fedora', 'Ubuntu']
    - dfe_has_gnome

- name: Set certificate file permissions
  ansible.builtin.file:
    path: "{{ item }}"
    owner: gnome-remote-desktop
    group: gnome-remote-desktop
    mode: '0600'
  loop:
    - /var/lib/gnome-remote-desktop/.local/share/gnome-remote-desktop/certificates/rdp-tls.key
    - /var/lib/gnome-remote-desktop/.local/share/gnome-remote-desktop/certificates/rdp-tls.crt
  when:
    - ansible_distribution in ['Fedora', 'Ubuntu']
    - dfe_has_gnome

- name: Configure grdctl to use TLS certificate
  ansible.builtin.command:
    cmd: grdctl --system rdp set-tls-cert /var/lib/gnome-remote-desktop/.local/share/gnome-remote-desktop/certificates/rdp-tls.crt
  when:
    - ansible_distribution in ['Fedora', 'Ubuntu']
    - dfe_has_gnome
  failed_when: false
  changed_when: false

- name: Configure grdctl to use TLS key
  ansible.builtin.command:
    cmd: grdctl --system rdp set-tls-key /var/lib/gnome-remote-desktop/.local/share/gnome-remote-desktop/certificates/rdp-tls.key
  when:
    - ansible_distribution in ['Fedora', 'Ubuntu']
    - dfe_has_gnome
  failed_when: false
  changed_when: false
