---
# Disk I/O optimizations for VMs

- name: Create udev rule for I/O scheduler
  ansible.builtin.copy:
    dest: /etc/udev/rules.d/60-vm-disk-scheduler.rules
    content: |
      # Set none scheduler for virtual disks
      ACTION=="add|change", KERNEL=="sd[a-z]|vd[a-z]", ATTR{queue/scheduler}="none"
    mode: '0644'
  when:
    - ansible_distribution in ['Fedora', 'Ubuntu']
    - ansible_virtualization_role == 'guest'

- name: Reload udev rules
  ansible.builtin.command: udevadm control --reload-rules
  changed_when: false
  when:
    - ansible_distribution in ['Fedora', 'Ubuntu']
    - ansible_virtualization_role == 'guest'
