---
# GRUB boot optimizations for VMs

- name: Backup GRUB configuration
  ansible.builtin.copy:
    src: /etc/default/grub
    dest: /etc/default/grub.backup.vm-optimizer
    remote_src: true
    force: false
  when:
    - ansible_distribution in ['Fedora', 'Ubuntu']
    - ansible_virtualization_role == 'guest'

- name: Set GRUB timeout to 1 second
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_TIMEOUT='
    line: 'GRUB_TIMEOUT=1'
    state: present
  when:
    - ansible_distribution in ['Fedora', 'Ubuntu']
    - ansible_virtualization_role == 'guest'

- name: Add VM-optimized kernel parameters
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX="elevator=none no_timer_check"'
    state: present
  when:
    - ansible_distribution in ['Fedora', 'Ubuntu']
    - ansible_virtualization_role == 'guest'

- name: Update GRUB configuration (Fedora BIOS)
  ansible.builtin.command: grub2-mkconfig -o /boot/grub2/grub.cfg
  when:
    - ansible_distribution == 'Fedora'
    - ansible_virtualization_role == 'guest'
    - ansible_facts.firmware == 'bios'
  failed_when: false
  changed_when: false

- name: Update GRUB configuration (Fedora UEFI)
  ansible.builtin.command: grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg
  when:
    - ansible_distribution == 'Fedora'
    - ansible_virtualization_role == 'guest'
    - ansible_facts.firmware == 'uefi'
  failed_when: false
  changed_when: false

- name: Update GRUB configuration (Ubuntu)
  ansible.builtin.command: update-grub
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_virtualization_role == 'guest'
  failed_when: false
  changed_when: false
