---
# Docker CE installation for Fedora

- name: Remove Podman (conflicts with Docker)
  ansible.builtin.dnf:
    name:
      - podman
      - podman-docker
      - buildah
      - skopeo
      - toolbox
    state: absent

- name: Add Docker CE repository
  ansible.builtin.command:
    cmd: dnf config-manager addrepo --from-repofile=https://download.docker.com/linux/fedora/docker-ce.repo --overwrite
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker CE
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Install Docker Desktop (if GUI present)
  block:
    - name: Check if GNOME is running
      ansible.builtin.command: pgrep -x gnome-shell
      register: gnome_check
      failed_when: false
      changed_when: false

    - name: Download Docker Desktop RPM
      ansible.builtin.get_url:
        url: "{{ dfe_docker_desktop_url_fedora }}"
        dest: /tmp/docker-desktop.rpm
        mode: '0644'
      when: gnome_check.rc == 0 and dfe_docker_install_desktop

    - name: Install Docker Desktop
      ansible.builtin.dnf:
        name: /tmp/docker-desktop.rpm
        state: present
        disable_gpg_check: true
      when: gnome_check.rc == 0 and dfe_docker_install_desktop

    - name: Remove Docker Desktop RPM
      ansible.builtin.file:
        path: /tmp/docker-desktop.rpm
        state: absent
      when: gnome_check.rc == 0 and dfe_docker_install_desktop
  when: dfe_docker_install_desktop | default(true)
