---
# Docker CE installation - main entry point

- name: Add Docker repository
  ansible.builtin.include_tasks:
    file: repository.yml

- name: Install Docker packages
  ansible.builtin.include_tasks:
    file: packages.yml

- name: Install Docker Desktop (GUI)
  ansible.builtin.include_tasks:
    file: desktop.yml
  when: dfe_docker_install_desktop | default(true)

- name: Configure Docker
  ansible.builtin.include_tasks:
    file: configure.yml

- name: Verify Docker installation
  ansible.builtin.include_tasks:
    file: verify.yml
