---
# Install Docker packages for all supported platforms

# Fedora - Remove Podman first (conflicts)
- name: Remove Podman (Fedora)
  ansible.builtin.dnf:
    name:
      - podman
      - podman-docker
      - buildah
      - skopeo
      - toolbox
    state: absent
  when: ansible_distribution == 'Fedora'

# Fedora - Install Docker CE
- name: Install Docker CE (Fedora)
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  when: ansible_distribution == 'Fedora'

# Ubuntu - Install Docker CE
- name: Install Docker CE (Ubuntu)
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  when: ansible_distribution == 'Ubuntu'

# macOS - Docker is installed via cask in repository.yml (Docker Desktop)
# No additional packages needed for macOS
