---
# Docker CE installation for Ubuntu

- name: Install prerequisites for Docker repository
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: true

- name: Create Docker GPG keyring directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: docker
    state: present

- name: Update APT cache after adding Docker repo
  ansible.builtin.apt:
    update_cache: true

- name: Install Docker CE
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Install Docker Desktop (if GUI present)
  block:
    - name: Check if GNOME is running
      ansible.builtin.command: pgrep -x gnome-shell
      register: gnome_check
      failed_when: false
      changed_when: false

    - name: Download Docker Desktop DEB
      ansible.builtin.get_url:
        url: https://desktop.docker.com/linux/main/amd64/docker-desktop-amd64.deb
        dest: /tmp/docker-desktop.deb
        mode: '0644'
      when: gnome_check.rc == 0 and dfe_docker_install_desktop

    - name: Install Docker Desktop
      ansible.builtin.apt:
        deb: /tmp/docker-desktop.deb
        state: present
      when: gnome_check.rc == 0 and dfe_docker_install_desktop

    - name: Remove Docker Desktop DEB
      ansible.builtin.file:
        path: /tmp/docker-desktop.deb
        state: absent
      when: gnome_check.rc == 0 and dfe_docker_install_desktop
  when: dfe_docker_install_desktop | default(true)
