---
galaxy_info:
  author: HyperSec
  description: DFE base developer environment setup
  company: HyperSec
  license: Apache-2.0
  min_ansible_version: "2.16"
  platforms:
    - name: Fedora
      versions: ['42']
    - name: Ubuntu
      versions: ['noble']
    - name: macOS
      versions: ['all']

dependencies: []
