---
galaxy_info:
  author: HyperSec
  description: Docker CE installation and configuration for DFE developers
  company: HyperSec
  license: Apache-2.0
  min_ansible_version: "2.9"
  platforms:
    - name: Fedora
      versions:
        - 42
    - name: Ubuntu
      versions:
        - noble
    - name: Debian
      versions:
        - all

dependencies: []
